
name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" 
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: blandoncj
          outputs: |
            ./dist/github-contribution-grid-snake.svg

      - name: Push to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "./dist/github-contribution-grid-snake.svg"
